# Generated by Django 3.2.6 on 2021-08-21 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectionsLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=250)),
                ('status_server', models.CharField(max_length=50, null=True)),
                ('session_state', models.CharField(max_length=100, null=True)),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField()),
                ('action', models.CharField(choices=[('LI', 'Log-In'), ('LO', 'Log-Out'), ('SRC', 'Solicitud de restablecimiento de contraseña'), ('ERC', 'Enviar código de recuperación de Contraseña'), ('VRC', 'Validar código de recuperación de contraseña'), ('RC', 'Restablecer contraseña'), ('OIU', 'Obtener informacion de usuario')], default='LI', max_length=250)),
            ],
            options={
                'verbose_name': 'Registro de Conexión',
                'verbose_name_plural': 'Logs de Solicitudes de Conexión',
                'ordering': ['pk'],
            },
        ),
    ]
