# Generated by Django 3.2.6 on 2021-08-21 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectionslogs',
            name='action',
            field=models.CharField(choices=[('LI', 'Log-In'), ('LO', 'Log-Out'), ('SRC', 'Solicitud de restablecimiento de contraseña'), ('ERC', 'Enviar código de recuperación de Contraseña'), ('VRC', 'Validar código de recuperación de contraseña'), ('RC', 'Restablecer contraseña'), ('OIU', 'Obtener información de usuario')], default='LI', max_length=250),
        ),
    ]
