# Generated by Django 3.2.6 on 2021-08-21 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigator', '0002_alter_connectionslogs_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectionslogs',
            name='session_state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='connectionslogs',
            name='status_server',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
