# Generated by Django 3.2.6 on 2021-08-21 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigator', '0005_investigator_id_keyclock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investigator',
            name='id_keyclock',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
