# Generated by Django 3.2.6 on 2021-08-21 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigator', '0006_alter_investigator_id_keyclock'),
    ]

    operations = [
        migrations.AddField(
            model_name='investigator',
            name='curp',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
