# Generated by Django 3.2.6 on 2021-08-21 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investigator', '0007_investigator_curp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Codes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField()),
                ('used', models.DateTimeField()),
                ('investigator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='codes', to='investigator.investigator')),
            ],
            options={
                'verbose_name': 'Código de activación',
                'verbose_name_plural': 'Listado de códigos',
                'ordering': ['pk'],
            },
        ),
    ]
