# Generated by Django 2.2.11 on 2021-08-18 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de servidor')),
                ('memory', models.IntegerField(verbose_name='Memoria')),
                ('volume', models.IntegerField(verbose_name='Volumen')),
                ('cpu', models.IntegerField(verbose_name='CPU')),
                ('price', models.FloatField(verbose_name='Precio')),
                ('so', models.CharField(max_length=100, verbose_name='Sistema Operativo')),
            ],
            options={
                'verbose_name': 'Servidor',
                'verbose_name_plural': 'Listado de servidores',
                'ordering': ['pk'],
            },
        ),
    ]
