# Generated by Django 2.2.11 on 2021-08-18 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='created',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='server',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='server',
            name='updated',
            field=models.DateTimeField(null=True),
        ),
    ]
